### ISSUE TITLE
Loading only Debian

### ISSUE THREAD

**Issue by farazfazli** [maruos/android_device_lge_hammerhead#1]
Hey!

Great job on this project! I would like to know if there's any easy way I can have just Debian load on the device (without chroot, I will be using the phone through adb shell/ssh), not both Android and Debian simultaneously.

Please let me know. Thanks!

**Comment by pdsouza** [comment]
Hi! 

Maru OS was really designed for running both systems at the same time and on separate displays since Android is optimized for the phone interface and Debian for the desktop interface. Debian also piggybacks on Android for interacting with the hardware by leveraging Android's drivers. Without Android running, the phone will not display anything, so you can't connect to WiFi, Bluetooth, etc. The overhead from running Android isn't bad if you are only using ssh, since Android will remain idle most of the time.

If you still only want to run Debian, you can try this:
1. First set up your WiFi connection with Android
2. Start the Debian desktop in the backgound in Settings > Dashboard (Note: starting the desktop in the background without an HDMI screen will be available in the upcoming release; v0.2.4 and older will require you to first connect to an HDMI screen to start the desktop)
3. Shut down the Android framework by running `stop` from a root adb shell
4. ssh into Debian with `ssh maru@<device-ip>`

Hope this helps and thanks for checking out Maru OS!

**Comment by farazfazli** [comment]
Hi,

Thanks for the swift response. I am currently running Ubuntu Touch and a reverse SSH tunnel to access the Android device from anywhere. I would like to know - on the Debian included in Maru OS, can I simply apt-get packages? With Ubuntu Touch, I had to make the image writable first. Also, am I able to run freeglut?

What's the timeline like on the next release? I am really looking forward to it. Thanks again!

**Comment by pdsouza** [comment]
Yup, apt-get just works out of the box.

I can't comment on the timeline, but the next version is being finalized at the moment and a release should follow before too long!

**Comment by pdsouza** [comment]
Closing this since it's pretty old. Feel free to reopen if you have any further questions on this.
